mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from accounts.views import login_view, logout_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('A3rafkolytk.urls')),
    url(r'^departments/', include('departments.urls')),
    url(r'^union/', include('union.urls')),
    url(r'^teams/', include('teams.urls')),
    url(r'^technical/', include('techncial.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^comments/', include('comments.urls')),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/posts/urls.py
from django.conf.urls import url, include
from . import views

app_name='posts'

urlpatterns = [
    url(r'^$', views.post_list , name='post_list'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<id>\d+)/$', views.post_detail , name='detail'),
    url(r'^(?P<id>\d+)/edit/$', views.post_update, name='post_update'),
]

mysite/posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from comments.models import Comment
from django.contrib.contenttypes.models import ContentType


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    image = models.FileField(null=True, blank=True)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True , auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False , auto_now_add=True)
    
    def __unicode__(self):
        return self.title
    
    def get_absolute_url(self):
        return "/posts/%s/" %(self.id)
    
    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs
    
    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type
    

mysite/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
        ]

mysite/posts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.contenttypes.models import ContentType
from comments.forms import CommentForm
from comments.models import Comment
from .models import Post
from .forms import PostForm


def post_list(request):
    queryset_list = Post.objects.all().order_by("-timestamp")
    paginator = Paginator(queryset_list, 10)
    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)
        
        
    context ={
        "object_list" : queryset,
        "title" : "List"
    }
    return render(request, 'posts/index.html', context)


def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        return redirect("/posts") #HttpResponseRedirect(instance.get_absolute_url())
    context ={
        "form" : form,
    }
    return render(request, 'posts/post_form.html', context)


def post_update(request, id=None):
    instance = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None, request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())
    context ={
        "instance": instance,
        "title" : instance.title,
        "form" : form
    }
    return render(request, 'posts/post_form.html', context)


def post_detail(request, id=None):
    instance = get_object_or_404(Post, id=id)
    
    initial_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id
    }
    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get("object_id")
        content_data = form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None
            
        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()
                
        
        new_comment, created = Comment.objects.get_or_create(user = request.user, content_type=content_type, object_id=obj_id, content=content_data, parent=parent_obj)
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
    
    comments = instance.comments
    context ={
        "instance": instance,
        "title" : instance.title,
        "comments": comments,
        "comment_form": form,
    }
    return render(request, 'posts/post_detail.html', context)

mysite/posts/templates/posts/comment_thread.html
{% extends "A3rafkolytk/header.html" %}
{% block title%}Reply To comment{% endblock %}
{% block content %}
<div style="align-content: center; background-color: beige; margin: 10% 10%; border-radius: 25px;">
    <div class="panel panel-info">
          <div class="panel-heading">
              <h4>
                  {{ comment.content }}
                  <h5>
                      By: {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 1 %} {{ comment.children.count }} Replies | {% elif comment.children.count == 1 %}1 Reply{% endif %}
                  </h5>
              </h4>
          </div>
        <div class="panel-body">
            {% for child_comment in comment.children %}
                <blockquote>
                    <p>{{ child_comment.content }}</p>
                    <footer style="color: lightseagreen;">By: {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago</footer>
                </blockquote>
            {% endfor %}
            <hr style="height:1px; border:none; color:lightblue; background-color:lightblue;">
            {% if request.user.is_authenticated %}
                <form method="post" action="." style="text-align: center;">
                    {% csrf_token %}
                    {{form}}
                    <input type="hidden" name="parent_id" value="{{ comment.id }}">
                    <input type="submit" value="Reply" class="btn btn-default">
                </form>
            {% else %}
                <p>You Must Login To Reply</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

mysite/posts/templates/posts/form.html
{% extends "A3rafkolytk/header.html" %}

{% block title%}Login{% endblock %}

{% block content %}
<div style="align-content: center; background-color: beige; margin: 20% 10%; border-radius: 25px;">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h1>{{ title }}</h1>
        </div>
        <div class="panel-body">
            <form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="{{ title }}">
            </form>
        </div>
    </div>
</div>
{% endblock %}

mysite/posts/templates/posts/index.html
{% extends "A3rafkolytk/header.html" %}

{% block title%}Community{% endblock %}

{% block content %}
    
    <div style="align-content: center; background-color: beige; margin: 10% 10%; border-radius: 25px;">
        <div style="padding-top: 2.5%; text-align: center;">
            <h2>Here we comunicate with each other to make a strong bond between us ^__^</h2>
        </div>
        <div class="col-sm-offset-5">
            <a href="{% url 'posts:post_create' %}" style="font-size: 200%;">Create New Post</a>
        </div>
        <hr style="height:1px; border:none; color:cadetblue; background-color:cadetblue;">
        <div class="col-sm-offset-3" style="margin-right: 20%;">
        {% for obj in object_list %}
            <div class="panel panel-info">
                <div class="panel-heading"><a href='{{ obj.get_absolute_url }}' style="font-size: 150%;">{{ obj.title }}</a><br></div>
                <div class="panel-body">
                    {% if obj.image %}
                        <img src="{{ obj.image.url }}" class="img-responsive">
                    {% endif %}
                    <p style="font-size: 150%; color: darkslategray;">{{obj.content}}</p>
                    <footer style="color: lightseagreen;">
                        posted by: {{obj.user}} | {{obj.timestamp|timesince}} ago
                        {% if not obj.timestamp == obj.updated%}
                        <br>
                        updated: {{obj.updated|timesince}} ago
                        {% endif %}
                    </footer>
                    {% if request.user == obj.user %}
                        <a href="{% url 'posts:post_update' obj.id %}">Update</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        </div>
        <br>
        <div class="pagination">
            <span class="step-links">
                <span class="current">
                    Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
                </span>
                {% if object_list.has_previous %}
                    <a href="?page=1">&laquo; first</a> | <a href="?page={{ object_list.previous_page_number }}">previous</a>
                    {% if object_list.has_next %} | {% endif %}
                {% endif %}
                
                {% if object_list.has_next %}
                    <a href="?page={{ object_list.next_page_number }}">next</a> | <a href="?page={{ object_list.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
    
{% endblock %}

mysite/posts/templates/posts/post_detail.html
{% extends "A3rafkolytk/header.html" %}
{% block title%}Post Detail{% endblock %}
{% block content %}
<div style="align-content: center; background-color: beige; margin: 10% 10%; border-radius: 25px;">
    <div class="panel panel-info">
        <div class="panel-heading"><h1 style="text-align: center;">{{ title }}</h1></div>
        <div class="panel-body">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h4>
                    Posted by: {{ instance.user }}<br>
                    since:{{ instance.timestamp|timesince }}
                    {% if not instance.timestamp == instance.updated %}
                    <br>Updated since:{{ instance.updated|timesince }}
                    {% endif %}
                    </h4>
                </div>
                <div class="panel-body">
                    <p>{{ instance.content }}</p>
                    {% if instance.image %}
                        <div style="height: 50%; width: 50%" class="col-sm-offset-3">
                            <a href="{{ instance.image.url }}">
                                <img src="{{ instance.image.url }}" class="img-responsive">
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>    
    
    <div class="panel panel-info">
        <div class="panel-heading"><h4>Comments</h4></div>
        <div class="panel-body">
            {% if request.user.is_authenticated %}
            <div style="text-align: center;">
                <form method="post" action=".">{% csrf_token %}
                    {{comment_form}}
                    <input type="submit" value="Post Comment" class="btn btn-default">
                </form>
            </div>
            {% else %}
                <p>You Must Login To Comment</p>
            {% endif %}
            <hr style="height:1px; border:none; color:cadetblue; background-color:cadetblue;">
            <div>
                {% for comment in comments %}
                    <blockquote>
                        <p>{{ comment.content }}</p>
                        <p style="color: lightseagreen">By: {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 1 %} {{ comment.children.count }} Replies | {% elif comment.children.count == 1 %}1 Reply | {% endif %}<a href="{{ comment.get_absolute_url }}">Reply</a></p>
                    </blockquote>
                    <hr style="height:1px; border:none; color:lightblue; background-color:lightblue;">
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

mysite/posts/templates/posts/post_form.html
{% extends "A3rafkolytk/header.html" %}
{% block title%}Post{% endblock %}
{% block content %}

<div style="align-content: center; background-color: beige; margin: 10% 10%; border-radius: 25px;">
    <div class="panel panel-primary">
        <div class="panel-heading">
        <h1>Post Maker</h1>
        </div>
        <div class="panel-body">
            {% if request.user.is_authenticated %}
                <form method="post" action="" enctype="multipart/form-data">{% csrf_token %}

                    {{ form.as_p }}
                    <input type="submit" value="Post">

                </form>
            {% else %}
                <p>You Have To Login First</p>
            {% endif %}
        </div>
    </div>
</div>
    
{% endblock %}