mysite/A3rafkolytk/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'A3rafkolytk'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

mysite/departments/urls.py
from django.conf.urls import url, include
from . import views

app_name='departments'

urlpatterns = [
    url(r'^computer/$', views.computer, name='computer'),
    url(r'^electric/$', views.electric, name='electric'),
    url(r'^mecha/$', views.mecha, name='mecha'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from accounts.views import login_view, logout_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('A3rafkolytk.urls')),
    url(r'^departments/', include('departments.urls')),
    url(r'^union/', include('union.urls')),
    url(r'^teams/', include('teams.urls')),
    url(r'^technical/', include('techncial.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^comments/', include('comments.urls')),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/posts/urls.py
from django.conf.urls import url, include
from . import views

app_name='posts'

urlpatterns = [
    url(r'^$', views.post_list , name='post_list'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<id>\d+)/$', views.post_detail , name='detail'),
    url(r'^(?P<id>\d+)/edit/$', views.post_update, name='post_update'),
]

mysite/teams/urls.py
from django.conf.urls import url
from . import views

app_name = 'teams'

urlpatterns = [
    url(r'^teams/$', views.Teamo.as_view(), name='index'),
]

mysite/techncial/urls.py
from django.conf.urls import url
from . import views

app_name = 'technical'

urlpatterns = [
    url(r'^technical/$', views.Techo.as_view(), name='index'),
]

mysite/union/urls.py
from django.conf.urls import url
from . import views

app_name = 'union'

urlpatterns = [
    url(r'^union/$', views.Union.as_view(), name='index'),
]

mysite/A3rafkolytk/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

mysite/A3rafkolytk/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render


def index(request):
    return render(request, 'A3rafkolytk/home.html')

mysite/A3rafkolytk/templates/A3rafkolytk/header.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>
    {% block title %}
    {% endblock %}
  </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'A3rafkolytk/css/animate.css' %}" type="text/css" />
  <script src="{% static 'A3rafkolytk/js/wow.min.js' %}"></script>
  <script>
    new WOW().init();
  </script>
</head>
    
    <style>
        .font {
            font-family: 'Cookie', cursive;
        }
        body {
            background : url("{% static 'A3rafkolytk/img/AlexBG.jpg' %}");
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 1400px 650px;
        }
    </style>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand font">A3rafkolytk</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active">
            <a href="{% url 'A3rafkolytk:index' %}">
                <span class="glyphicon glyphicon-home"aria-hidden="true"></span>&nbsp;Home
            </a>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="glyphicon glyphicon-education" aria-hidden="true"></span>&nbsp;Departments
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" style="background-color: lightgray;">
                <li><a href="{% url 'departments:computer' %}" style="color: black;">Computer Engineering</a></li>
                <li><a href="{% url 'departments:electric' %}" style="color: black;">Electricity Engineering</a></li>
                <li><a href="{% url 'departments:mecha' %}" style="color: black;">Mechanical Engineering</a></li>
                <li><a href="{% url 'posts:post_list' %}" style="color: black;">Community</a></li>
            </ul>
        </li>
        <li>
            <a href="{% url 'union:index' %}"  >
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;Student's Union
            </a>
        </li>
        <li>
            <a href="{% url 'technical:index' %}"  >
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>&nbsp;Technical Teams
            </a>
        </li>
        <li>
            <a href="{% url 'teams:index' %}"  >
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp;Teams and Chapters
            </a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#about"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>&nbsp;About</a></li>
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        {% else %}
        <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

    <div>
        {% block content %}
        {% endblock %}
    </div>
<div>
    <p style=" font-family: 'Gaegu', cursive; color: white; ">© 2018 CSED21, Inc. All rights reserved.<br>
       © 2018 molahez,wakel,sman,gemy. All rights reserved.<br>
       Trademarks referenced herein belong to their respective owners</p>
</div>
</body>
</html>

mysite/A3rafkolytk/templates/A3rafkolytk/home.html
{% extends "A3rafkolytk/header.html" %}
{% block title%}E3rafkolytk{% endblock %}
<link href="https://fonts.googleapis.com/css?family=Gaegu" rel="stylesheet">

{% block content %}
<div style="margin-top: 100px; margin-right: 500px; margin-left: 500px;">
    <h1 class="font wow fadeInDown" style="text-align: center; font-size: 100px; color: antiquewhite;">E3rafkolytk</h1>
</div>
<hr style="margin-left: 600px; margin-right: 600px; height:5px; border:none; color:lightcoral; background-color:lightcoral;" class="font fadeInDown animated"/>
<div style="padding-left: 50px; padding-right:20px; padding-top: 45px; height: 150px; border-radius: 20px;  background-color: forestgreen;
            margin-left: 150px; margin-right: 100px;" class="wow fadeInLeft" data-wow-duration="2s" data-wow-delay=".1s">
    <p style="animation-delay: 2s; font-size: 19px; color: black; align-content: center" class="wow lightSpeedIn" data-wow-delay="1s"><b>
        Here we are helping you to keep up with the college,knowing every event handled by different teams &amp; chapters<br>
        knowing the news of Student union &amp; Technical teams,knowing more about internships,courses </b>
    </p>
</div>
<div style="margin: 250px 125px; background-color: cadetblue; padding-bottom: 100px; padding-left: 100px;padding-right: 100px; padding-top: 10px; border-radius: 25px;" id="about" class="wow jackInTheBox" data-wow-duration="2s" data-wow-delay=".1s">
    <h1 style="font-family: 'Gaegu', cursive; text-align: center; color: darkred;">Who Are We?!</h1>
    <p style="text-align: center; font-family: 'Gaegu', cursive; color: brown; font-size: 19px"><b>
        We are Students of CSED21 and we were given a project to carry out a website that helps community  <br>
           So we decided to make this website and we hope that any one visits this website never hesitate to come again
        </b>
    </p>
</div>
{% endblock %}